![Logo](logoGalileo.png "Logo")
***      
# TEXT MINING & IMAGE RECOGNITION *Seccion* "V"
## *LABORATORIO # 3*
##### **Pedro Josué Chamale Perez** - __23000478__

In [1]:
import cv2
import os
import numpy as np
import pandas as pd

In [2]:
dataPath = 'C:/Users/ChamalePJ/Documents/Maestría/Trimestre III/Text Mining & Image Recognition/Laboratorios/Lab3_Desarrollo/Problema2/Datos/'
archivos = os.listdir(dataPath)

In [3]:
[file for file in os.listdir(dataPath) if '.txt' in file]
files = [os.path.join(dataPath, file) for file in os.listdir(dataPath) if '.txt' in file]

In [4]:
df = pd.DataFrame()
for i in range(0,len(files)):
    #Se aplica la expresión regular en el separador de la lectura del DataFrame y se van agregando archivo por archivo
    df = df.append(pd.read_csv(files[i], sep = '[-\/.]', index_col=False, header=None), ignore_index=True)

C:\Users\ChamalePJ\AppData\Local\Temp\ipykernel_16220\2819405369.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = df.append(pd.read_csv(files[i], sep = '[-\/.]', index_col=False, header=None), ignore_index=True)
C:\Users\ChamalePJ\AppData\Local\Temp\ipykernel_16220\2819405369.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.read_csv(files[i], sep = '[-\/.]', index_col=False, header=None), ignore_index=True)
C:\Users\ChamalePJ\AppData\Local\Temp\ipykernel_16220\2819405369.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warni

In [11]:
df.columns = ['Day','Month','Year']
df

Day Month  Year
0       23     2  2017
1       21    11  2016
2       12     2  2017
3        6     6  2016
4        4     5  2018
...    ...   ...   ...
20995    8     5  2016
20996   28     9  2016
20997   14     4  2019
20998   11    12  2014
20999   13     8  2018

[21000 rows x 3 columns]

In [12]:
#Verificando los valores para la columna Dia
df['Day'].unique()

array([23, 21, 12,  6,  4, 19,  2, 20, 11,  5, 31, 24, 13, 25,  3, 29, 10,
        1, 30, 16,  8,  7, 22,  9, 28, 27, 15, 14, 18, 17, 26],
      dtype=int64)

In [13]:
#Verificando los valores para la columna Mes
df['Month'].unique()

array([2, 11, 6, 5, 12, 4, 9, 10, 1, 7, 3, 8, 'Nov', 'Apr', 'Jun', 'Dec',
       'Feb', 'Mar', 'May', 'Sep', 'Aug', 'Jan', 'Jul', 'Oct'],
      dtype=object)

In [14]:
#Verificando los valores para la columna Año
df['Year'].unique()

array([2017, 2016, 2018, 2015, 2019, 2014], dtype=int64)

In [23]:
#Transformando datos de la columna Mes a valores numericos
df.replace(['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],[1,2,3,4,5,6,7,8,9,10,11,12], inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21000 entries, 0 to 20999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Day     21000 non-null  int64
 1   Month   21000 non-null  int64
 2   Year    21000 non-null  int64
dtypes: int64(3)
memory usage: 492.3 KB


In [33]:
print("El valor promedio de las fechas que se encuentran en los 21 archivos es de: \n")
df.mean()

El valor promedio de las fechas que se encuentran en los 21 archivos es de: 



Day        15.624762
Month       6.466476
Year     2016.686905
dtype: float64